# Generated by Django 5.1.1 on 2024-09-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_author_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Dessert', 'Dessert'), ('Main Course', 'Main Course'), ('Breakfast', 'Breakfast'), ('vegertrian', 'vegetrian'), ('appetizer', 'Appetizer'), ('salad', 'salad'), ('drink', 'Drink')], max_length=50),
        ),
    ]
